- backend
nodejs:
  build:
    context: .
  restart: always
  environment:
    - MONGODB=mongodb://mongo-image/food
#      - VIRTUAL_HOST=edenhub.co
#      - VIRTUAL_PORT=3000
#      - LETSENCRYPT_HOST=edenhub.co
  links:
    - mongo-image
  ports:
    - "5200:3000"
  networks:
    - backend
networks:
backend:
 driver: bridge